# Generated by Django 5.1.4 on 2024-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(default='Opción por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(default='Opción por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(default='Opción por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(default='Opción por defecto', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
