# Generated by Django 5.1.4 on 2024-12-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('questions', '0002_question_option_1_question_option_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='game',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
