# Generated by Django 5.1.3 on 2024-12-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_question_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='question_count',
        ),
    ]
