# Generated by Django 5.1.3 on 2024-12-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_used_questions_alter_game_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_questions',
            field=models.IntegerField(default=10),
        ),
    ]
