# Generated by Django 5.1.4 on 2024-12-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_used_questions_alter_game_current_question'),
        ('questions', '0003_alter_question_options_alter_question_option_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
